# Generated by Django 5.1.1 on 2026-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsummary',
            name='term',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='termsummary',
            unique_together={('student', 'term', 'session')},
        ),
    ]
