# Generated by Django 5.1.1 on 2026-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_termsummary_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsummary',
            name='attendance',
        ),
        migrations.AddField(
            model_name='termsummary',
            name='days_absent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of days the student was absent'),
        ),
        migrations.AddField(
            model_name='termsummary',
            name='days_present',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of days the student was present'),
        ),
    ]
